# ============================================================
# POSTGRESQL - NEON
# ============================================================
#db.url=jdbc:postgresql://ep-restless-hall-aehwldwn-pooler.c-2.us-east-2.aws.neon.tech:5432/sysventas?sslmode=require
db.url=jdbc:postgresql://ep-falling-sea-b44jiymv-pooler.c-6.us-east-2.aws.neon.tech:5432/SysVentas?sslmode=require

db.username=neondb_owner
db.password=npg_pi3rS9gPhKmL
# ============================================================
# DDL
# ============================================================
db.ddl.auto=false
db.ddl.script=schema_sv.sql